// business_trip-frontend_react/src/app/Footer/Footer.tsx
import React, { useEffect } from 'react';
import useApi from '../../hooks/useApi';
import './footer.scss';

export function Footer() {
  const { api, isLoading, handleFetchApi } = useApi();

  useEffect(() => {
    async function loadApi() {
      if (!isLoading) {
        await handleFetchApi();
      }
    }
    loadApi();
  }, []);

  return (
    <React.Fragment>
      <div className="footer bg-dark">
        <div className="row">
          <div className="col">Projekt für die Bachelorarbeit</div>
          <div className="col center">
            {isLoading ? (
              <div>...</div>
            ) : (
              <div>
                {api.framework}:{api.version}
              </div>
            )}
          </div>
          <div className="col left">
            &copy; Maximilian Schreiter {new Date().getFullYear()}
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

export default Footer;

// business-trip-frontend/src/app/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../services/api/api.service';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
})
export class FooterComponent implements OnInit {
  public version: any;
  isLoading: boolean = true;

  constructor(protected apiServce: ApiService) {}

  ngOnInit(): void {
    this.apiServce.getVersion().subscribe(
      (data: any) => {
        console.log(data);
        this.version = `${data.framework} v${data.version}`;
      },
      (err) => {},
      () => {
        this.isLoading = false;
      },
    );
    this.isLoading = false;
  }
}

<div class="footer bg-dark">
  <div class="row">
    <div class="col">Projekt für die Bachelorarbeit</div>
    <div className="col center">
      <div *ngIf="isLoading">...</div>
      <div *ngIf="!isLoading">{{ version }}</div>
    </div>
    <div class="col left">&copy; Maximilian Schreiter</div>
  </div>
</div>
